/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2021-09-30

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_tim.h"
#include "misc.h"
/* Private macro */
/* Private variables */
static int i = 0;
/* Private function prototypes */
/* Private functions */

void Delay(uint32_t nCount) {
    while (nCount--) {
    }
}

static void initLedPorts(void) {
    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);

    GPIO_InitTypeDef gpioConf;
    gpioConf.GPIO_Pin = GPIO_Pin_12 | GPIO_Pin_13 | GPIO_Pin_14 | GPIO_Pin_15;
    gpioConf.GPIO_Mode = GPIO_Mode_OUT;
    gpioConf.GPIO_Speed = GPIO_Speed_100MHz;
    gpioConf.GPIO_OType = GPIO_OType_PP;
    gpioConf.GPIO_PuPd = GPIO_PuPd_NOPULL;
    GPIO_Init(GPIOD, &gpioConf);

}

void TIM2_IRQHandler(void) {
    if (TIM_GetITStatus(TIM2, TIM_IT_Update) != RESET) {
        TIM_ClearITPendingBit(TIM2, TIM_IT_Update);
        i++;
    }
}

static void initTimerOneTwoSecond(void) {
    NVIC_InitTypeDef nvic_struct;
    nvic_struct.NVIC_IRQChannel = TIM2_IRQn;
    nvic_struct.NVIC_IRQChannelPreemptionPriority = 0;
    nvic_struct.NVIC_IRQChannelSubPriority = 1;
    nvic_struct.NVIC_IRQChannelCmd = ENABLE;
    NVIC_Init(&nvic_struct);

    RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);

    TIM_Cmd(TIM2, DISABLE);
    TIM_TimeBaseInitTypeDef tim_struct;
    tim_struct.TIM_Prescaler = 1750 - 1;
    tim_struct.TIM_Period = 10000 - 1;
    tim_struct.TIM_ClockDivision = 0;
    tim_struct.TIM_CounterMode = TIM_CounterMode_Up;
    TIM_TimeBaseInit(TIM2, &tim_struct);
    TIM_ITConfig(TIM2, TIM_IT_Update, ENABLE);
    TIM_Cmd(TIM2, ENABLE);
}

static void initTimerHalfSecond(void) {
    NVIC_InitTypeDef nvic_struct;
    nvic_struct.NVIC_IRQChannel = TIM2_IRQn;
    nvic_struct.NVIC_IRQChannelPreemptionPriority = 0;
    nvic_struct.NVIC_IRQChannelSubPriority = 1;
    nvic_struct.NVIC_IRQChannelCmd = ENABLE;
    NVIC_Init(&nvic_struct);

    RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);

    TIM_Cmd(TIM2, DISABLE);
    TIM_TimeBaseInitTypeDef tim_struct;
    tim_struct.TIM_Prescaler = 4200 - 1;
    tim_struct.TIM_Period = 10000 - 1;
    tim_struct.TIM_ClockDivision = 0;
    tim_struct.TIM_CounterMode = TIM_CounterMode_Up;
    TIM_TimeBaseInit(TIM2, &tim_struct);
    TIM_ITConfig(TIM2, TIM_IT_Update, ENABLE);
    TIM_Cmd(TIM2, ENABLE);
}

static void initButton(void) {
    GPIO_InitTypeDef gpioConf;

    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
    gpioConf.GPIO_Pin = GPIO_Pin_0;
    gpioConf.GPIO_Mode = GPIO_Mode_IN;

    GPIO_Init(GPIOA, &gpioConf);
}

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void) {
    /**
    *  IMPORTANT NOTE!
    *  The symbol VECT_TAB_SRAM needs to be defined when building the project
    *  if code has been located to RAM and interrupts are used.
    *  Otherwise the interrupt table located in flash will be used.
    *  See also the <system_*.c> file and how the SystemInit() function updates
    *  SCB->VTOR register.
    *  E.g.  SCB->VTOR = 0x20000000;
    */

    /* TODO - Add your application code here */

    //�������� ����� ��� �����������
    initLedPorts();
    initButton();

    int j = 0;
    /* Infinite loop */
    while (1) {
        if (GPIO_ReadInputDataBit(GPIOA, GPIO_Pin_0) == 0) {
            if (j == 0) {
                initTimerHalfSecond();
                if (i == 0) {
                    GPIO_SetBits(GPIOD, GPIO_Pin_15);
                } else if (i == 1) {
                    GPIO_ResetBits(GPIOD, GPIO_Pin_15);
                    GPIO_SetBits(GPIOD, GPIO_Pin_14);
                } else if (i == 2) {
                    GPIO_ResetBits(GPIOD, GPIO_Pin_14);
                    GPIO_SetBits(GPIOD, GPIO_Pin_12);
                } else if (i == 3) {
                    GPIO_ResetBits(GPIOD, GPIO_Pin_12);
                    GPIO_SetBits(GPIOD, GPIO_Pin_13);
                } else if (i == 4) {
                    GPIO_ResetBits(GPIOD, GPIO_Pin_12 | GPIO_Pin_13 | GPIO_Pin_14 | GPIO_Pin_15);
                    i = 0;
                }
                j++;
            } else if (j == 1) {
                initTimerOneTwoSecond();
                if (i == 0) {
                    GPIO_SetBits(GPIOD, GPIO_Pin_13);
                } else if (i == 1) {
                    GPIO_ResetBits(GPIOD, GPIO_Pin_13);
                    GPIO_SetBits(GPIOD, GPIO_Pin_12);
                } else if (i == 2) {
                    GPIO_ResetBits(GPIOD, GPIO_Pin_12);
                    GPIO_SetBits(GPIOD, GPIO_Pin_14);
                } else if (i == 3) {
                    GPIO_ResetBits(GPIOD, GPIO_Pin_14);
                    GPIO_SetBits(GPIOD, GPIO_Pin_15);
                } else if (i == 4) {
                    GPIO_ResetBits(GPIOD, GPIO_Pin_12 | GPIO_Pin_13 | GPIO_Pin_14 | GPIO_Pin_15);
                    i = 0;
                }
                j++;
            } else if (j == 2) {
                j = 0;
            }
            Delay(5000);
            while (GPIO_ReadInputDataBit(GPIOA, GPIO_Pin_0) == 0);
            Delay(5000);
        }
    }
}
